[package]

	name    = "ekke_merge_derive_example"
	version = "0.1.0"
	authors = [ "Naja Melan <najamelan@autistici.org>" ]
	edition = "2018"


[dependencies]

	ekke_merge        = { path = "../../../ekke_merge"        }
	ekke_merge_derive = { path = "../../../ekke_merge_derive" }
